BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE EQUIPMENTS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MAINTENANCE CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE EQUIPMENT_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE MAINTENANCE_SEQ';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -2289 THEN
            RAISE;
        END IF;
END;
/

CREATE SEQUENCE EQUIPMENT_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE MAINTENANCE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE EQUIPMENTS (
    ID NUMBER(10) NOT NULL,
    NAME VARCHAR2(120) NOT NULL,
    TYPE VARCHAR2(80) NOT NULL,
    STATUS VARCHAR2(30) NOT NULL,
    PURCHASE_DATE DATE,
    CONSTRAINT PK_EQUIPMENTS PRIMARY KEY (ID)
);

CREATE TABLE MAINTENANCE (
    ID NUMBER(10) NOT NULL,
    EQUIPMENT_ID NUMBER(10) NOT NULL,
    MAINTENANCE_DATE DATE NOT NULL,
    MAINTENANCE_TYPE VARCHAR2(80) NOT NULL,
    COST NUMBER(10, 2) NOT NULL,
    CONSTRAINT PK_MAINTENANCE PRIMARY KEY (ID),
    CONSTRAINT FK_MAINTENANCE_EQUIPMENT FOREIGN KEY (EQUIPMENT_ID) REFERENCES EQUIPMENTS(ID)
);
